[package]
name = "multiply_by_scalar"
version = "0.1.0"
authors = ["costa-wang <3162284013@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl = { version = "0.19.3" }
ocl_extras = { version = "0.1.1" }
